### ISSUE TITLE
Installing Modules for all Users in Program Files

### ISSUE THREAD

**Issue by andzi** [saveenr/VisioPowerShell#1]
it would be nice find description on **Installing Modules for all Users in Program Files** if somebody want a module to be available to all user accounts on the computer, i.e. how to install the module in the Program Files location: `$EnvProgramFiles\WindowsPowerShell\Modules\<Module Folder>\<Module Files>`

**Comment by kilasuit** [comment]
@andzi by default if you run in an admin session

``` powershell
Install-Module Visio
```

it will install the module in the `$EnvProgramFiles\WindowsPowerShell\Modules\` location

**Comment by saveenr** [comment]
Thanks @kilasuit for the comment.

@andzi Visio Powershell switched to using the PowerShell Gallery as the install mechanism, moving away from the old MSI-based installer.

This means that using Install-Module Visio will by default install for all users (note that it must be run as admin for this to succeed). I've updated the Visio PowerShell docs (https://github.com/saveenr/VisioPowerShell/wiki) to reflect this change.
