### ISSUE TITLE
Visio 2016 x64 compatibility

### ISSUE THREAD

**Issue by janegilring** [saveenr/VisioPowerShell#2]
Hi,

Does the module support Visio 2016 x64?

I`m getting this error when running New-VisioApplication on Windows 10 with PowerShell 5.1.14393.576 : Could not load file or assembly 'Microsoft.Office.Interop.Visio, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c' or one of its de
pendencies. The system cannot find the file specified.

Version info: 
Get-Package -Name *Visio* | fl Name,Version,ProviderName,Source

Name         : Microsoft Visio Professional 2016 - en-us
Version      : 16.0.4266.1003
ProviderName : Programs
Source       : 

Name         : Visio
Version      : 1.3.2
ProviderName : PowerShellGet
Source       : https://www.powershellgallery.com/api/v2/

**Comment by saveenr** [comment]
It does not. The way the the module is built with .NET code it is specifically bound to the 32 bit version.

**Comment by janegilring** [comment]
Ah, thanks.

Maybe the 32-bit requirement could be added to the first sentence in the Wiki?
_Visio PowerShell module (aka VisioPS) is a PowerShell module that simplifies automating tasks with Visio 2010 (32-bit) and above._

**Comment by saveenr** [comment]
Good idea! Will add that note to the wiki
